name: Auto Assign PR Reviewers
 
on:
  pull_request:
    types: [ opened, reopened ]
  workflow_dispatch:

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign
        run: |
          pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          curl --location --request POST 'https://api.github.com/repos/${{ github.repository }}/pulls/'"$pull_number"'/requested_reviewers' \
               --header 'Authorization: token ${{ secrets.SELF_API_TOKEN }}' \
               --header 'Content-Type: application/json' \
               --data-raw '{
                   "team_reviewers": [ "team-groot-tigers", "team-groot-lions" ]
               }'
